// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPF6ZWkWOsWLZMovJ_nwIUSbO0ZFiUUks',
    appId: '1:119946037764:web:8831273e6242e4fc90c351',
    messagingSenderId: '119946037764',
    projectId: 'musicplayer1234',
    authDomain: 'musicplayer1234.firebaseapp.com',
    storageBucket: 'musicplayer1234.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANnj6zBR45M-wuYa4Z2HJt6cVAG2lJJ90',
    appId: '1:119946037764:android:7fe69fc46606401e90c351',
    messagingSenderId: '119946037764',
    projectId: 'musicplayer1234',
    storageBucket: 'musicplayer1234.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcTFEsjhAIuDIez1pURF_zkelbsdHU2OA',
    appId: '1:119946037764:ios:71cb6e6c8b22581790c351',
    messagingSenderId: '119946037764',
    projectId: 'musicplayer1234',
    storageBucket: 'musicplayer1234.appspot.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcTFEsjhAIuDIez1pURF_zkelbsdHU2OA',
    appId: '1:119946037764:ios:71cb6e6c8b22581790c351',
    messagingSenderId: '119946037764',
    projectId: 'musicplayer1234',
    storageBucket: 'musicplayer1234.appspot.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPF6ZWkWOsWLZMovJ_nwIUSbO0ZFiUUks',
    appId: '1:119946037764:web:a05438adaec7fd3690c351',
    messagingSenderId: '119946037764',
    projectId: 'musicplayer1234',
    authDomain: 'musicplayer1234.firebaseapp.com',
    storageBucket: 'musicplayer1234.appspot.com',
  );
}
